### ISSUE TITLE
Override built in mermaid renderer?

### ISSUE THREAD

**Issue by luckman212** [gregzuro/obsidian-kroki#1]
Hi @gregzuro & thank you for making this plugin! Very useful.

I would like to use the Kroki plugin to render my mermaid diagrams since it seems to do a slightly better job than the built in module. But, I find that even if I enable `mermaid` type in Kroki settings, it is only used **once** (upon first launch). Switching to another note causes Obsidian to fall back to its native mermaid renderer again.

Do you know any way to avoid this?

#### Example - Kroki
![image](https://user-images.githubusercontent.com/1992842/125172474-f14b2380-e187-11eb-86ac-119fc4b3f70a.png)

#### vs Native
_ignore those colored boxes, that is just some custom css that I was playing with to try to debug why the diagram were cutting off_
![image](https://user-images.githubusercontent.com/1992842/125172497-10e24c00-e188-11eb-86be-41e5c8d658cf.png)

**Comment by gregzuro** [comment]
> I find that even if I enable `mermaid` type in Kroki settings, it is only used **once** (upon first launch). Switching to another note causes Obsidian to fall back to its native mermaid renderer again.
> 
> Do you know any way to avoid this?

It seems as though obsidian handles multiple renderers a bit randomly.

I've been thinking that I'd have a setting to specify the name of each diagram type so that collisions like this can be avoided. 

I'll add that ASAP.

Cheers,

**Comment by gregzuro** [comment]
Fixed in https://github.com/gregzuro/obsidian-kroki/commit/9cff6fd067caec65ed9982c07f19220cd1e10024

**Comment by luckman212** [comment]
@gregzuro thank you for this, but at least for me, it's not working. In my prefs, all the `language` input boxes were blank. I tried inputting eg `kroki-mermaid` to override the mermaid renderer, but nothing gets displayed- also there are some console errors.  screenshot:

**Comment by luckman212** [comment]
I figured it might be something with the `data.json` (prefs). Trashed my old one and built a new one, it works now. I think it's because the old prefs never populated the `krokiBlockName` key in the json. Might be good to put a note about this.

#### old prefs (not working)
```json
{
  "blockName": "mermaid",
  "description": "",
  "enabled": true,
  "obsidianBlockName": "kmermaid",
  "prettyName": "Mermaid",
  "toggle": {
    "disabled": false,
    "on": true,
    "toggleEl": {}
  },
  "url": "https://github.com/knsv/mermaid"
}
```

#### new prefs (working)
```json
{
  "description": "",
  "enabled": true,
  "krokiBlockName": "mermaid",
  "obsidianBlockName": "kmermaid",
  "prettyName": "Mermaid",
  "toggle": {
    "disabled": false,
    "on": true,
    "toggleEl": {}
  },
  "url": "https://github.com/knsv/mermaid"
}
```
