### ISSUE TITLE
support export to pdf in obsidian

### ISSUE THREAD

**Issue by Wanxp** [gregzuro/obsidian-kroki#12]
- envirment:
  - ubuntu: 22.04
  - obsidian: v0.14.6
  - obsidian-kroki: 1.2.2
- problem
  - pictures not show in export pdf
- action
 - write down content in markdown file as below
```md
\```plantuml
[*] --> State1: init
State1 --> State2: action1
State2 --> State1: action2
State2 --> [*]: end
\```
``` 
  - and picture can normaly show in obsidian preview mode
  - click top-right three-nod button  and choose export to pdf
  - picture not show in pdf

**Comment by gregzuro** [comment]
I've tested this in Macos and the exported diagram in visible in the PDF just fine.

I'll try ubuntu in a bit and let you know what I find.
