### ISSUE TITLE
Support for diagrams.net

### ISSUE THREAD

**Issue by onnyyonn** [gregzuro/obsidian-kroki#13]
Kroki has experimental support for https://diagrams.net as `/diagramsnet` . Will you consider adding it in the plugin?

**Comment by julianmueller** [comment]
There is a plugin, that does this: https://github.com/jensmtg/obsidian-diagrams-net

**Comment by onnyyonn** [comment]
Thanks for the suggestion. But those plugins are not the same. They include the figure as an image. The Kroki plugin, on the other hand, includes a codeblock, that is rendered as the figure. I prefer the Kroki approach, because I want my notes to be "text-only".

Fortunately, implementing diagrams.net support in this plugin was trivial and I have already made a pull request. Unfortunately the dev is not active it seems and it hasn't been merged.

**Comment by julianmueller** [comment]
You are right, they only add the finished file (and also add an interface for the editor).

I'd be very interested in your appoach of text-only. Is it possible, that you fork the project and extend it with your pull-request? As you are familiar with the implementation, you might generously continue this plugin? :)

**Comment by onnyyonn** [comment]
My fork with the diagram.net integration is here https://github.com/onnyyonn/obsidian-kroki . But you have to install it manually. Unfortunately, at this moment I don't have enough time to maintain a hard-fork. But I may consider that in future if no one else steps up to maintain this plugin.

**Comment by gregzuro** [comment]
Sorry for the negligence here.  I'll get this merged.

**Comment by gregzuro** [comment]
Does anyone have a kroki server with diagramnets enabled? 

I (tried to) enable it on my server, but it's not working, so I can't test this.

I'll take a crack at this again soon, but until I hear that someone has a working server, it's pending.

**Comment by onnyyonn** [comment]
@gregzuro thanks for taking time to look into this. I'll try to set up a temporary Kroki server for testing it, sometime in the next week.

**Comment by gregzuro** [comment]
added in [06d2478](https://github.com/gregzuro/obsidian-kroki/commit/06d2478e24d0161eebba22a46250f2ceac88849c)

**Comment by gregzuro** [comment]
Great idea.  Will add that soon.

**Comment by gregzuro** [comment]
@julianmueller:

I've added an example diagram to the test file.  

I am not at all familiar with the diagrams.net syntax or the method used to extract the 'source code' of the diagrams for use with this plugin.  

For the moment, this is, unfortunately, an exercise for the reader.

BTW: do you have access to a kroki server with the diagrams.net functionality enabled?

**Comment by julianmueller** [comment]
For me your example diagram.net is not rendering, but only showing as a codeblock. And I guess there is an option mising in the plugin to explicitely enable the `diagramsnet` type (as there are options for all the other supported diagram types).
Furthermore, I dont have access to a running kroki server, and i dont think that https://kroki.io/#try lets you type in diagrams.net code. Maybe @onnyyonn can help?

**Comment by gregzuro** [comment]
> For me your example diagram.net is not rendering, but only showing as a codeblock. 

diagramsnet is disabled by default in this release of the plugin. 
See below for how to enable.

> And I guess there is an option mising in the plugin to explicitely enable the `diagramsnet` type (as there are options for all the other supported diagram types). 

Uninstall, then reinstall the plugin.
The setting will then appear. (Don't forget to disable and enable the plugin after changing the settings to enable diagramsnet.)
Not sure why this is necessary. 
Am looking into it.

>Furthermore, I dont have access to a running kroki server, and i dont think that https://kroki.io/#try lets you type in diagrams.net code. Maybe @onnyyonn can help?

If you don't have access to a server that has diagramsnet enabled (kroki.io does not have it enabled), then I think you'll just get a blank result in render view.
You can run one locally in docker to test if you like...
