### ISSUE TITLE
Language List

### ISSUE THREAD

**Issue by Xevion** [gregzuro/obsidian-kroki#16]
While the Kroki diagram list is comprehensive, figuring out which language the codeblock wants is not intuitive. For example, C4 Plantuml and Plantuml are `c4plantuml` and `kroki-plantuml` respectively. How are we intended to guess which one?

Additionally, while an example is provided, it's hundreds of lines long! Not ideal for figuring out which language I'm supposed to specify.

Please amend the plugin documentation to assist with genuine usage.

**Comment by gregzuro** [comment]
The differences between `c4plantuml` and `kroki-plantuml` are unknown to me and are not the concern of the plugin.  Links to each language's specifics are given in the settings.  LMK if I am misunderstanding your concern.

As for the long example, I don't disagree.  If you'd like to make a PR with them split out, I promise to promptly merge it. :)
