### ISSUE TITLE
how to code fence

### ISSUE THREAD

**Issue by AG4GitHub** [gregzuro/obsidian-kroki#6]
Hi, I installed the plugin in Obsidian. Copied some samples and included the text in ```. No graphics displayed. Do I need to add a keyword after the first limiter ''';' which one. tried kroki, no success

**Comment by gregzuro** [comment]
The file https://github.com/gregzuro/obsidian-kroki/blob/master/kroki-test.md is an example.

If you make that a note, or copy that into one, they should all render.

LMK how it goes.

**Comment by AG4GitHub** [comment]
Thank you so much for your attention. Actually I tried the above already, copy and paste several code blocks and switched to preview. Nothing is rendered. Can there be any conflict with another plugin?
Cheers, stay safe

**Comment by gregzuro** [comment]
I suppose that is possible. Have you observed the console to see if anything is there?

(https://forum.obsidian.md/t/how-to-access-the-console/16703/2)

**Comment by AG4GitHub** [comment]
Thanks will check
